### ISSUE TITLE
How Can i Use property of Type Enum with OData Parser ?

### ISSUE THREAD

**Issue by syn-sanket-mistry** [codecutout/StringToExpression#6]
I am getting error when trying to use ODataParser on Property of type enum. e.g., SomeType eq 1

**Comment by alex-davies** [comment]
@syn-sanket-mistry unfortunately it doesn't support enums at the moment, however it would be a sensible addition. I'm open to pull requests otherwise you will have a to wait a few days for me to find some time to implement it.

As a work around you can define your contract as an int (or string) rather than an enum in the meantime

**Comment by syn-sanket-mistry** [comment]
I managed to do following...

new BinaryOperatorDefinition(
                    name:"EQ",
                    regex: @"eq",
                    orderOfPrecedence:11,
                    expressionBuilder: 
                    (left,right) => {
                        if (left.Type.IsEnum)
                        {
                            return Expression.Equal(left, Expression.Convert(right, left.Type));
                        }
                        return Expression.Equal(left, right);
                    }),
                new BinaryOperatorDefinition(
                    name:"NE",
                    regex: @"ne",
                    orderOfPrecedence:12,
                    expressionBuilder:
                    (left,right) => {
                        if (left.Type.IsEnum)
                        {
                            return Expression.NotEqual(left, Expression.Convert(right, left.Type));
                        }
                        return Expression.NotEqual(left, right);
                    }),

**Comment by syn-sanket-mistry** [comment]
This seems to be working fine with MongoDb engine as well. However this seems more of a heck.

**Comment by alex-davies** [comment]
There is now some built-in enum support for both numbers and strings. The change is in version 1.1.0

If you want you can see the changes at https://github.com/codecutout/StringToExpression/pull/7. The  number to enum parsing isn't too different to what you have, it just has a bit more logic to handle nullables and to make sure we only apply it on numbers.

The string conversion is a bit more complicated and have just limited it to handling string constants only, but even that should cover most cases.

**Comment by syn-sanket-mistry** [comment]
Thanks for the updated version
